version: '3.0'
services:

  db:
    image: ansible/postgresql
    container_name: database
    volumes:
      - starter-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRESQL_USER = user
      - POSTGRESQL_PASSWORD = password
      - POSTGRESQL_DATABASE = database
  web:
    build: ./DesafioG2WApplication
    container_name: web-app
    environment:
      - DB_SERVER=db
    ports:
      - "8080:8080"
    links:
      - db