version: '3.0'
services:

  db:
    image: mysql
    container_name: database
    volumes:
      - starter-data:/var/lib/mysql/data
    ports:
    - "3306:3006"
    environment:
      - MYSQL_ROOT_PASSWORD = pass
      - MYSQL_USER = user
      - MYSQL_PASSWORD = password
      - MYSQL_DATABASE = database
  web:
    build: ./DesafioG2WApplication
    container_name: web-app
    environment:
      - DB_SERVER=db
    ports:
      - "8080:8080"
    links:
      - db